"""initial_schema

Revision ID: 514131ceac41
Revises: 
Create Date: 2026-05-05 21:31:11.704211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '514131ceac41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=True),
    sa.Column('volatility_index', sa.Float(), nullable=True),
    sa.Column('trend_direction', sa.String(length=16), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('reliability', sa.Float(), nullable=True),
    sa.Column('api_endpoint', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sector_tag', sa.String(length=64), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('llm_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ci_score', sa.Float(), nullable=True),
    sa.Column('is_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('correlation_matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sector_a_id', sa.Integer(), nullable=False),
    sa.Column('sector_b_id', sa.Integer(), nullable=False),
    sa.Column('correlation', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('p_value', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('lag_days', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('window_days', sa.Integer(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sector_a_id'], ['sectors.id'], ),
    sa.ForeignKeyConstraint(['sector_b_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('computed_at', 'sector_a_id', 'sector_b_id', 'method', name='uq_corrmatrix_entry')
    )
    op.create_table('data_streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stream_type', sa.String(length=32), nullable=False),
    sa.Column('source_label', sa.String(length=64), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('time', 'source_label', name='uq_datastream_time_label')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('linked_sector_id', sa.Integer(), nullable=True),
    sa.Column('prediction_type', sa.String(length=32), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('predicted_direction', sa.String(length=16), nullable=True),
    sa.Column('predicted_magnitude', sa.String(length=32), nullable=True),
    sa.Column('features_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('realized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['linked_sector_id'], ['sectors.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sector_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_sector_id', sa.Integer(), nullable=False),
    sa.Column('target_sector_id', sa.Integer(), nullable=False),
    sa.Column('correlation_coeff', sa.Float(), nullable=True),
    sa.Column('lag_days', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('link_type', sa.String(length=32), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('last_computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_sector_id'], ['sectors.id'], ),
    sa.ForeignKeyConstraint(['target_sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_sector_id', 'target_sector_id', 'link_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sector_links')
    op.drop_table('predictions')
    op.drop_table('data_streams')
    op.drop_table('correlation_matrix')
    op.drop_table('articles')
    op.drop_table('sources')
    op.drop_table('sectors')
    # ### end Alembic commands ###
